baseURL = 'https://mingxn.github.io/aws-saa-c03/'
languageCode = 'en-us'
title = 'AWS SAA-C03 Exam Prep'

[params]
  description = 'Interactive question bank for AWS Solutions Architect Associate (SAA-C03) exam preparation'
  author = 'mingxn'

[menu]
  [[menu.main]]
    name = 'Practice Mode'
    url = '/practice/'
    weight = 1
  [[menu.main]]
    name = 'Exam Mode'
    url = '/exam/'
    weight = 2
  [[menu.main]]
    name = 'All Questions'
    url = '/questions/'
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow HTML in markdown for interactive elements
